[package]
name = "patchman"
version = "0.1.0"
edition = "2021"

[dependencies]
dark-light = "1.1.1"
iced = { version = "0.13.1", features = ["tokio", "image"] }
log = "0.4.22"
reqwest = "0.12.9"
rust-i18n = "3.1.2"
